### ISSUE TITLE
Missing declaration of the dimensions in Asset model

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-delivery-sdk-java#82]
### Brief bug description

Based on the [StackOverflow issue](https://stackoverflow.com/questions/57041685/com-fasterxml-jackson-databind-exc-unrecognizedpropertyexception-in-kentico-clou/57045406).

Probably related to #78

### Repro steps

When loading the item using i.e.:
```java
DeliveryClient client = new DeliveryClient("975bf280-fd91-488c-994c-2f04416e5ee3", "<YOUR_PREVIEW_API_KEY>"); 
ContentItem item = client.getItem("on_roasts").item;
```

the error is raised

```json
{
  "timestamp": "2019-07-15T14:05:11.645+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"width\" (class com.kenticocloud.delivery.Image), not marked as ignorable (3 known properties: \"description\", \"image_id\", \"url\"])\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.kenticocloud.delivery.ContentItemsListingResponse[\"items\"]->java.util.ArrayList[0]->com.kenticocloud.delivery.ContentItem[\"elements\"]->java.util.LinkedHashMap[\"section\"]->com.kenticocloud.delivery.RichTextElement[\"images\"]->java.util.LinkedHashMap[\"dd2f48ec-252a-41b9-badf-320c8d125c16\"]->com.kenticocloud.delivery.Image[\"width\"])"
}
```

### Expected behavior

No error should be raised.

### Additional context

It is probably caused by the missing if `width` and `height` declaration in [Asset model](https://github.com/Kentico/delivery-sdk-java/blob/master/delivery/src/main/java/com/kenticocloud/delivery/Asset.java) that has been [introduced in the Delivery API](https://github.com/Kentico/delivery-sdk-java/blob/master/delivery/src/main/java/com/kenticocloud/delivery/Asset.java)

**Comment by aweigold** [comment]
The error should be resolved by the merge of #78 .  Keeping this open to update the model.

**Comment by cunhazera** [comment]
I tried to push one commit to try to help, but I got an permission error.

**Comment by Simply007** [comment]
Thanks, @aweigold! Closing the issues then.
