### ISSUE TITLE
Migrate CI to https://travis-ci.com

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-delivery-sdk-java#89]
### Motivation

@kentico organization is migrating all of the repositories under the https://travis-ci.com/ from (https://travis-ci.org).

Context:
https://docs.travis-ci.com/user/migrate/open-source-repository-migration/
https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com/4305#4305

### Proposed solution

@aweigold - I wanted to notify you prior to the actual migration and sync with you if you are OK with that.
For all other Kentico repositories, the migration was one-click without any issue, I just wanted to confirm that you don't see any obstacles with the release process, or with the CI migration in general.

Once we agree on migration - I will perform it and adjust the readme badges and automatic checks for the repository.

### Additional context

Note: internal link: https://kentico.atlassian.net/browse/DEVREL-125

**Comment by aweigold** [comment]
@Simply007  Let's move forward with it.  If there are build issues (outside of one I know about regarding CIs on PRs), I can take care of them post-migration.

**Comment by Simply007** [comment]
Migration should be done.

I have created a pull request (#90) to change the badge as well as test the CI integration.
I have also changed the protected branch rule to use the new Travis check instead of the old one.

If everything look OK for you - please merge the pull request and close the issue. And the last repo remaining would be [java generators](https://github.com/Kentico/cloud-generators-java).

**Comment by aweigold** [comment]
@Simply007 closing this issue.  I'll work on new releases for the java generators as they have to be updated over the weekend.
