### ISSUE TITLE
Width and Height of Asset model missing

### ISSUE THREAD

**Issue by SmootherSpike** [Kentico/kontent-delivery-sdk-java#94]
The asset model does not provide the width and height of the image yet, which the api does provide via curl.

Please map those values correctly, we need this information to do our server side rendering correctly

**Comment by Simply007** [comment]
Probably related to https://github.com/Kentico/kontent-delivery-sdk-java/issues/82

**Comment by SmootherSpike** [comment]
It is written in the additional context, where the width and height is mentioned, but this has not been implemented yet

**Comment by petrsvihlik** [comment]
Thanks for reporting this @SmootherSpike !

There is an open PR with the change: #91

We'll try to merge & close it soon!

**Comment by SmootherSpike** [comment]
I have created an own pr for these changes, since i can not resolve the conflicts in the existing branch, because i can not push in this repository
Please take a look, we require those fields in our implementation
